### ISSUE TITLE
exclude yourself when calculating RTs (interactions)

### ISSUE THREAD

**Issue by egonw** [gedankenstuecke/twitter-analyser#16]
Because Twitter has a feature to RT yourself, to allow you to put some extra focus on a tweet, e.g. at some later time, to cover all time zones. And this looks silly:

![image](https://user-images.githubusercontent.com/26721/34193417-e4e905be-e553-11e7-941c-b2a863483726.png)

**Comment by gedankenstuecke** [comment]
Thanks for the suggestion! 

Just to clarify: The graph is based on replies. Twitter internally uses self-replies to mark threads, I think this is where these peaks come from. But I agree that these can be confusing and should be removed. :)

**Comment by aashaka** [comment]
According to me, having self-replies in the graph also provides valuable information. The number of self-replies may blow out-of-proportion and make the other lines look smaller, but that would happen for every out-of-proportion data line.

At the same time, they can definitely be confusing. I would like to work on removing the self-replies once @gedankenstuecke gives a go-ahead approval!

**Comment by gedankenstuecke** [comment]
Yeah, I agree that it's nice to have these self-replies being part of the visualizations but also see the case why people want to get rid of them. Please feel free to give it a try! 👍

**Comment by gedankenstuecke** [comment]
@egonw if you reprocess your graphs now it should exclude yourself 👍
