### ISSUE TITLE
Allow Hard Coding TZ

### ISSUE THREAD

**Issue by BenjaminHCCarr** [gedankenstuecke/twitter-analyser#17]
A lot of us avoid geo tagging due to the huge privacy problems, see [espi0n/tinfoleak](https://github.com/espi0n/tinfoleak) for one example.

That said, at least 99% of my tweets come from one TZ (UTC-4) / US-East. Allowing one to hardcode one TZ likely be a popular use case.

You code do something like:
pseudocode `{if geotags == null}` as a global check, then ignore timestamps and `lat`/`lon`, offer hard coded `TZ` OR graph everything in `UTC`, as that would also be accurate.

@danamlewis also expressed interest in the hardcoded by end user `TZ` option. It's not as useful for people like you who bounce around a lot, but could generate a lot more figures from the current code.

**Comment by gedankenstuecke** [comment]
Actually, ignoring seasonal fluctuations, only 50% of your tweets will be from UTC-4. Unless they gave up on daylight savings on the east coast. Otherwise it will be UTC-3 for those months. 
So specifying a single time zone isn’t practical.

**Comment by gedankenstuecke** [comment]
(For the same reason just plotting UTC isn’t meaningful either)
