### ISSUE TITLE
Use stacked area plots for percentages

### ISSUE THREAD

**Issue by BenjaminHCCarr** [gedankenstuecke/twitter-analyser#19]
One thing that may make looking at percentage changes over time like
`Tweet classifications`
![tweet classifications](https://user-images.githubusercontent.com/8225968/34214524-c1ee31ac-e570-11e7-96d3-c2d0dd3f313f.png)
https://twtr-analyser.herokuapp.com/tweet_display/index/05804139/

Would be to used a stacked area plot:
![data_visualization_stacked_area_charts](https://user-images.githubusercontent.com/8225968/34214571-e210dc6e-e570-11e7-9eea-b7add6dc35a9.png)

This would also be an interesting way to present any other percentage data, like `gender` gedankenstuecke/twitter-analyser#18, or further enhancements

**Comment by gedankenstuecke** [comment]
Stacked area charts make it much harder to read the individual percentages as it works with a shifting baseline. Regular line graphs are doing a better job of conveying that information (see also [this blogpost on the topic](https://www.perceptualedge.com/blog/?p=2239)).
