### ISSUE TITLE
Change retweet_gender to reply_gender.

### ISSUE THREAD

**Issue by troublemagnet** [gedankenstuecke/twitter-analyser#30]
I think there's a typo in analyser.py, in __main__ the last line should be `write_json_for_graph(reply_gender, 'gender_reply.json')` and not `write_json_for_graph(retweet_gender, 'gender_reply.json')`!

**Comment by gedankenstuecke** [comment]
Yes, you're right. It never actually runs as this is only used when you run `python analyser.py` but it would be good to clean that up in any case. Feel free to make a PR for that. :)
