### ISSUE TITLE
Check grammar/spelling

### ISSUE THREAD

**Issue by gedankenstuecke** [gedankenstuecke/twitter-analyser#35]
![](https://img.shields.io/badge/difficulty-easy-brightgreen.svg)
![](https://img.shields.io/badge/other-Documentation-blue.svg)

All contributions so far come from people for whom English is a foreign language.
Due to that there's probably room for some copy-editing to smoothen things out.
Having a native speaker read over the texts would be highly appreciated.
This goes both for the `README.md` that describes the setup for the development
environment as well as the texts on the website itself.

**Comment by aath0** [comment]
Maybe it's just me, but it'd be really helpful if you gave directly the link to the documents that people can proof-read :)

**Comment by gedankenstuecke** [comment]
Good point. Pure documentation can be found in: 

- [README.md](https://github.com/gedankenstuecke/twitter-analyser/blob/master/README.md)
- [INSTALL.md](https://github.com/gedankenstuecke/twitter-analyser/blob/master/INSTALL.md)
- [CONTRIBUTING.md](https://github.com/gedankenstuecke/twitter-analyser/blob/master/CONTRIBUTING.md)

The copy for the website itself is found in the different `html` templates. The corresponding folders are: 

- [`users`](https://github.com/gedankenstuecke/twitter-analyser/tree/master/users/templates/users)
- [`display`](https://github.com/gedankenstuecke/twitter-analyser/tree/master/tweet_display/templates/tweet_display)
- [`about`](https://github.com/gedankenstuecke/twitter-analyser/tree/master/twitteranalyser/templates/twitteranalyser)

**Comment by gedankenstuecke** [comment]
I'll close this one thanks to @QuLogic! 👍 🎉
