### ISSUE TITLE
New Twitter archive format unreadable

### ISSUE THREAD

**Issue by igorbrigadir** [gedankenstuecke/twitter-analyser#39]
The latest Twitter archive is structured differently, with tweets now in a `tweet.js` file in the archive zip. 

Current scripts & notebooks fail to load tweets from this format. Example with 4 tweets attached. 
[tweet.js.txt](https://github.com/gedankenstuecke/twitter-analyser/files/2881712/tweet.js.txt)

**Comment by gedankenstuecke** [comment]
Thanks for the heads up! I'll try downloading mine and will adapt the code asap! :)

**Comment by gedankenstuecke** [comment]
Mh... I can't reproduce it with my own, I get a zip file which has the `data/js/tweets/` subfolder with files named after `yyyy-mm.json`, e.g. `2008_04.js`

How many tweets do you have overall? (I wonder whether it only does the splitting if there's too many tweets)

**Comment by mldulaney** [comment]
I also get data/js/tweets :(

**Comment by madprime** [comment]
I'm guessing @igorbrigadir is https://twitter.com/igorbrigadir with 8.9k tweets. I've only done 4.5k tweets and mine are split by month in the tweets subdirectory. So I'm guessing it's not number of tweets.

**Comment by igorbrigadir** [comment]
I have a much older `yyyy-mm.json` format archive downloaded too, but for this one, I first requested and downloaded on `2019-02-01` if that helps figure out how new / old this is.

I'll request another one in a week or so to check again (current one won't expire until `2019-03-03`).

Here's a copy of the README.txt that comes inside: 
[README.txt](https://github.com/gedankenstuecke/twitter-analyser/files/2882209/README.txt)

**Comment by gedankenstuecke** [comment]
Oh, that looks totally different than the archive I got (and I requested mine just now and it's in the format I described above). 

Did you download yours from the bottom of this page? https://twitter.com/settings/account 

Because there's also some `download your twitter data` button on https://twitter.com/settings/your_twitter_data 

The first link is the one that contains only your tweets and none of the other data for me. Currently waiting to see what comes out of the second one.

**Comment by igorbrigadir** [comment]
Ah, that's it! - I totally missed how there's 2 different places for your "Twitter Archive".

https://twitter.com/settings/account "Your Tweet Archive" is in the correct format, and everything works on twarxiv. The zipfile starts with your user_id like `495430242_...`

https://twitter.com/settings/your_twitter_data "Download your Twitter data" archive is the one with `tweets.js` format, and contains a lot more information it seems (this is the one i tried to use first). These archives are called `twitter-2019-02-01-...`

**Comment by gedankenstuecke** [comment]
Ah, great. That solves the issue! I think the `your_twitter_data` one is the one that's GDPR compliant and gives you a lot of additional information that Twitter has about yourself, such as your likes (`like.js`) and even your direct messages sent/received (`direct-message.js`).
